[mcp_servers.context7-mcp]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.tts]
command = "tts-mcp"

[mcp_servers.tts.env]
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
HIMITHER_TTS_LOG_FILE = "/tmp/tts-mcp-server.log"
RUST_LOG = "debug"
XDG_RUNTIME_DIR = "/run/user/1000"

[mcp_servers.ez-web-search-mcp]
command = "sh"
args = ["-c", "node ${HOME}/.mcphub/servers/ez-web-search-mcp/build/index.js"]

[projects."/home/gnarus/d/dotfiles"]
trust_level = "trusted"

[projects."/home/gnarus/d/himither"]
trust_level = "trusted"
