#!/usr/bin/env bash

pwd=$(pwd)

configPaths=(
  .config/nvim
  .config/mcphub
  .config/opencode
  .config/awesome
  .config/gtk-3.0
  .config/eww .config/leftwm
  .config/ghostty/config
  .config/himither

  .tmux.conf.local
  .wezterm.lua
  .config/picom.conf
  .zshrc
  .gitconfig

  .local/bin/clip
  .local/bin/getfonts.sh
  .local/bin/git-ac
)

for p in ${configPaths[*]}; do
  rm -rf ~/$p
  ln -s $pwd/$p ~/$p
done
