#!/usr/bin/env bash

pwd=$(pwd)
configPaths=(.config/nvim .config/zellij .config/eww .config/leftwm .config/alacritty .tmux.conf .wezterm.lua .zshrc .gitconfig)

for p in ${configPaths[*]}
do
  rm -rf ~/$p
  ln -s $pwd/$p ~/$p
done
