general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 0
    dots_center = true
    fade_on_empty = false
    placeholder_text = Password
    position = 0, -40
    halign = center
    valign = center
}
