#!/bin/sh

export SCRIPTPATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

leftwm-command "UnloadTheme"

cleanup() {
  if [ -x "$(command -v eww)" ]; then
    eww -c $SCRIPTPATH/.config/eww kill &> /dev/null
    sleep 1
    pkill eww
  fi

  pkill picom
  pkill dunst
}

cleanup &> /tmp/ignorant_down_errors.log

echo "✅ Theme shutdown complete"
