#!/bin/sh

export SCRIPTPATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

leftwm-command "UnloadTheme"

if [ -x "$(command -v eww)" ]; then
  eww -c $SCRIPTPATH/.config/eww kill &> /dev/null
  sleep 1
  Kill eww
fi

pkill stalonetray
pkill picom
pkill dunst

echo "✅ Theme shutdown complete"
