#!/bin/sh

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# start eww daemon
eww daemon &

# start system tray viewer, if one exists
type stalonetray &> /dev/null && stalonetray &

# start compositor
type picom &> /dev/null && picom --no-vsync &

# Set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

feh --randomize --bg-fill "$SCRIPTPATH"/wallpaper/*.png

eww open-many bar bar1 bar2
