#!/bin/sh

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# start system tray viewer, if one exists
type stalonetray &> /dev/null && stalonetray &

#boot picom compositor if it exists
if [ -x "$(command -v picom)" ]; then
  picom --no-vsync --config=$SCRIPTPATH/.config/picom/picom.conf &>/dev/null &
fi

# Set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v feh)" ]; then
  feh --randomize --bg-fill "$SCRIPTPATH"/wallpaper/*.png
fi

# Start dunst.
if [ -x "$(command -v dunst)" ]; then
  dunst -conf ${SCRIPTPATH}/.config/dunst/dunstrc.ini &
  sleep 1
  notify-send -u low "Let's get ignant!"
fi

start_eww() {
  if [ -x "$(command -v eww)" ]; then
    eww -c $SCRIPTPATH/.config/eww daemon &
    eww -c $SCRIPTPATH/.config/eww open-many bar bar1
  else
    notify-send '`eww` not found, please install it (system wide "/usr/bin") and try again.'
    return 1
  fi
}

start_eww &> /tmp/eww_error.log
